name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: [ 7.4, 8.0 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-
            composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Check code style
        run: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --verbose --diff --dry-run
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: Run tests
        run: vendor/bin/phpunit
